runtime: nodejs14
handlers:
  - url: /(.*\.(js|css|svg|png)(|\.map))$
    static_files: dist/my-app/\1
    upload: dist/my-app/(.*)(|\.map)
  - url: /.*
    static_files: dist/my-app/index.html
    upload: dist/my-app/.*
